-- Create database
CREATE DATABASE IF NOT EXISTS ga_clinic CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE ga_clinic;

-- Create province table
CREATE TABLE IF NOT EXISTS province (
    PROVINCE_CODE VARCHAR(13) NOT NULL,
    PROVINCE_NAME VARCHAR(255) NULL,
    PRIMARY KEY (PROVINCE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create ampher table
CREATE TABLE IF NOT EXISTS ampher (
    AMPHER_CODE VARCHAR(11) NOT NULL,
    AMPHER_NAME VARCHAR(255) NULL,
    PROVINCE_CODE VARCHAR(13) NULL,
    PRIMARY KEY (AMPHER_CODE),
    FOREIGN KEY (PROVINCE_CODE) REFERENCES province(PROVINCE_CODE) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create tumbol table
CREATE TABLE IF NOT EXISTS tumbol (
    TUMBOL_CODE VARCHAR(11) NOT NULL,
    PROVINCE_CODE VARCHAR(13) NULL,
    TUMBOL_NAME VARCHAR(37) NULL,
    AMPHER_CODE VARCHAR(11) NULL,
    zipcode VARCHAR(7) NULL,
    PRIMARY KEY (TUMBOL_CODE),
    FOREIGN KEY (PROVINCE_CODE) REFERENCES province(PROVINCE_CODE) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (AMPHER_CODE) REFERENCES ampher(AMPHER_CODE) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Create patient1 table
CREATE TABLE IF NOT EXISTS patient1 (
    HNCODE VARCHAR(10) NOT NULL,
    IDNO VARCHAR(25) NULL,
    PRENAME VARCHAR(25) NULL,
    NAME1 VARCHAR(100) NULL,
    SURNAME VARCHAR(100) NULL,
    SEX VARCHAR(10) NULL,
    BDATE VARCHAR(10) NULL,
    AGE INT UNSIGNED NULL,
    BLOOD_GROUP1 VARCHAR(10) NULL,
    OCCUPATION1 VARCHAR(100) NULL,
    ORIGIN1 VARCHAR(50) NULL,
    NATIONAL1 VARCHAR(50) NULL,
    RELIGION1 VARCHAR(50) NULL,
    STATUS1 VARCHAR(50) NULL,
    WEIGHT1 INT NULL,
    HIGH1 INT UNSIGNED NULL,
    CARD_ADDR1 VARCHAR(100) NULL,
    CARD_TUMBOL_CODE VARCHAR(10) NULL,
    CARD_AMPHER_CODE VARCHAR(10) NULL,
    CARD_PROVINCE_CODE VARCHAR(10) NULL,
    ADDR1 VARCHAR(100) NULL,
    TUMBOL_CODE VARCHAR(10) NULL,
    AMPHER_CODE VARCHAR(10) NULL,
    PROVINCE_CODE VARCHAR(10) NULL,
    ZIPCODE VARCHAR(10) NULL,
    TEL1 VARCHAR(100) NULL,
    EMAIL1 VARCHAR(100) NULL,
    DISEASE1 VARCHAR(255) NULL,
    DRUG_ALLERGY VARCHAR(255) NULL,
    FOOD_ALLERGIES VARCHAR(255) NULL,
    PRIMARY KEY (HNCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;